from .subjects import subjects_keyboard
from .settings_keyboard import settings_keyboard, settings_keyboard_subjects, settings_keyboard_subgroups, settings_keyboard_notifications, settings_keyboard_terms
from .edit_hw_keyboard import edit_hw_keyboard
from .calendar_keyboard import calendar_keyboard
from .show_homework import homework_kb_both, homework_kb_next_week
